[package]
name = "epass"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aes-gcm = "0.10.2"
dirs = "5.0.1"
termion = "1.5.6"
colored = "2.0.0"
rpassword = "7.2.0"